 language: cpp
 compiler: clang
 before_install: 
 - sudo apt-get update -qq
 - sudo apt-get install -qq libsfml-dev libboost-all-dev libgtest-dev google-mock
 script: mkdir -p build && cd build && rm -rf * && cmake .. && make