
sudo: false

matrix:
  fast_finish: true
  include:

  - os: linux
    env: CXX=clang++-3.7
    addons: { apt: { packages: ["clang-3.7", "libstdc++-5-dev", "valgrind"], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-precise-3.7"] } }

  - os: linux
    dist: precise
    env: CXX=clang++-3.8
    addons: { apt: { packages: ["clang-3.8", "libstdc++-6-dev", "valgrind"], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-precise-3.8"] } }

  - os: linux
    dist: precise
    env:  CXX=clang++-3.9
    addons: { apt: { packages: ["clang-3.9", "libstdc++-6-dev", "valgrind"], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-precise-3.9"] } }

  - os: linux
    dist: precise
    env: CXX=clang++-4.0
    addons: { apt: { packages: ["clang-4.0", "libstdc++-6-dev", "valgrind"], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-trusty-4.0"] } }

  - os: linux
    dist: precise
    env: CXX=g++-5
    addons: { apt: { packages: ["g++-5", "libstdc++-5-dev", "valgrind"], sources: ["ubuntu-toolchain-r-test"] } }

  - os: linux
    dist: precise
    env: CXX=g++-6
    addons: { apt: { packages: ["g++-6", "libstdc++-6-dev", "valgrind"], sources: ["ubuntu-toolchain-r-test"] } }

  - os: linux
    dist: trusty
    env: CXX=g++-7
    addons: { apt: { packages: ["g++-7", "libstdc++-7-dev", "valgrind"], sources: ["ubuntu-toolchain-r-test"] } }

  - os: linux
    dist: trusty
    env: CXX=g++-7 VARIANT=coverage
    addons: { apt: { packages: ["g++-7", "libstdc++-7-dev", "valgrind"], sources: ["ubuntu-toolchain-r-test"] } }

  - os: osx
    osx_image: xcode7.3
    env: CXX=clang++

  - os: osx
    osx_image: xcode8.3
    env: CXX=clang++

  - os: osx
    osx_image: xcode9.1
    env: CXX=clang++




 language: cpp
 compiler: clang
 addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
 before_install: 
 - sudo apt-get update -qq
 - sudo apt-get install -qq libsfml-dev libboost-all-dev
 before_script:
  - wget http://sfml-dev.org/download/sfml/2.1/SFML-2.1-linux-gcc-64bits.tar.bz2 -O /tmp/sfml.tar.bz2
  - tar -xjvf /tmp/sfml.tar.bz2
  - sudo cp -r SFML-2.1/* /usr/
  - sudo apt-get install -y libjpeg62-dev libsndfile1-dev libglew1.5 libglew1.5-dev libfreetype6 libjpeg-turbo8 libjpeg8 libopenal-data libopenal1  libxrandr2 libxrender1 libsoil1 
 script:
 - mkdir -p build
 - cd build
 - cmake .. 
 - make
 notifications:
  email: false
