dist: trusty
sudo: required
language: cpp
compiler: gcc
env:
  global:
    # include $HOME/.local/bin for `aws`
    - PATH=$HOME/.local/bin:$PATH
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake
before_install:
 # set up awscli packages
  - pip install --user awscli
  - mkdir -p ~/$TRAVIS_BUILD_NUMBER
  - aws s3 sync s3://travis-build-stages-shared-storage-test/$TRAVIS_BUILD_NUMBER ~/$TRAVIS_BUILD_NUMBER 
install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libsfml-dev libboost-all-dev cmake
 - sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
 - sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
 - export CC=/usr/bin/gcc-7
 - export CXX=/usr/bin/g++-7
 - wget http://sfml-dev.org/download/sfml/2.1/SFML-2.1-linux-gcc-64bits.tar.bz2 -O /tmp/sfml.tar.bz2
 - tar -xjvf /tmp/sfml.tar.bz2
 - sudo cp -r SFML-2.1/* /usr/
 - sudo apt-get install -y libjpeg62-dev libsndfile1-dev libglew1.5 libglew1.5-dev libfreetype6 libjpeg-turbo8 libjpeg8 libopenal-data libopenal1  libxrandr2 libxrender1 libsoil1 
 
jobs:
  include:
    - stage: build
      script:
       - mkdir -p build
       - cd build
       - cmake .. 
       - make
       - mv ../bin ~/$TRAVIS_BUILD_NUMBER
    - stage: test
      script:
       - ~/$TRAVIS_BUILD_NUMBER/bin/TestPCGDemo
      after_success:
       - aws s3 rm --recursive s3://travis-build-stages-shared-storage-test/$TRAVIS_BUILD_NUMBER # clean up after ourselves
after_success:
  - aws s3 sync ~/$TRAVIS_BUILD_NUMBER s3://travis-build-stages-shared-storage-test/$TRAVIS_BUILD_NUMBER
notifications:
  email: false
